name       : tmuxp
version    : 1.12.1
release    : 4
source     :
    - https://files.pythonhosted.org/packages/3a/82/99028048067736a1b11c423787b3e21a351fdcd83df4f3938ce238ed9dc5/tmuxp-1.12.1.tar.gz : 078624c5ac7aa4142735f856fadb9281fcebb10e6b98d1be2b2f2bbd106613b9
license    : MIT
component  : system.utils
summary    : tmux session manager
description: |
    tmux session manager, built on libtmux.
homepage   : http://tmuxp.git-pull.com/
rundeps    :
    - python-click
    - python-colorama
    - python-libtmux
    - python-kaptan
    - tmux
build      : |
    %python3_setup
install    : |
    %python3_install
