name       : tmuxp
version    : 1.17.0
release    : 8
source     :
    - https://files.pythonhosted.org/packages/44/c3/6b367e516301bd90ce9f8a9f2faae171a576bf5cecf8aa1f5358011f6f4a/tmuxp-1.17.0.tar.gz : 4e63462a57e37d8134efeca51340fd4a91a28d0e2eff98e477afdc242c814b0b
license    : MIT
component  : system.utils
summary    : tmux session manager
description: |
    tmux session manager, built on libtmux.
homepage   : http://tmuxp.git-pull.com/
rundeps    :
    - python-colorama
    - python-libtmux
    - python-kaptan
    - tmux
build      : |
    %python3_setup
install    : |
    %python3_install
