name       : tmuxp
version    : 1.27.1
release    : 13
source     :
    - https://files.pythonhosted.org/packages/05/fd/31dfd84dafc409f6f4d0c52ae33ba300114d100c32799a42916facc6ef7c/tmuxp-1.27.1.tar.gz : ee8ca69828780c41f485eddd01f029602c4a13ed589e949f6ba6f9125bd0a939
license    : MIT
component  : system.utils
summary    : tmux session manager
description: |
    tmux session manager, built on libtmux.
homepage   : http://tmuxp.git-pull.com/
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-wheel
rundeps    :
    - python-colorama
    - python-libtmux
    - python-kaptan
    - tmux
networking : yes
environment: |
    export PYTHONUSERBASE=$workdir
    export PATH=$PATH:$workdir/bin/
setup      : |
    python3 -m pip install --user poetry
build      : |
    %python3_setup
install    : |
    %python3_install
