name       : tmuxp
version    : 1.18.1
release    : 10
source     :
    - https://files.pythonhosted.org/packages/55/81/a665e6d24442ccaad0d99e62ccaa2842d90b7f372cb293d80480ddb5852e/tmuxp-1.18.1.tar.gz : 7923a26da7766d6359e044a79029d3f882dcb7a2a9f47ffffce72f3ec708809a
license    : MIT
component  : system.utils
summary    : tmux session manager
description: |
    tmux session manager, built on libtmux.
homepage   : http://tmuxp.git-pull.com/
rundeps    :
    - python-colorama
    - python-libtmux
    - python-kaptan
    - tmux
build      : |
    %python3_setup
install    : |
    %python3_install
