name       : tmuxp
version    : 1.9.2
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/t/tmuxp/tmuxp-1.9.2.tar.gz : dd19536c8abb506bc411232f9dcabdedb863270f0ee26fb468555980140ec243
license    : MIT
component  : system.utils
summary    : tmux session manager
description: |
    tmux session manager, built on libtmux.
rundeps    :
    - python-click
    - python-colorama
    - python-libtmux
    - python-kaptan
    - tmux
build      : |
    %python3_setup
install    : |
    %python3_install
