name       : tmuxp
version    : 1.16.2
release    : 7
source     :
    - https://files.pythonhosted.org/packages/74/b0/df8299dc1ff34863ea4ee0bd6d63d352697b0bfea5b4edbaa7c91b7afb00/tmuxp-1.16.2.tar.gz : c42399c042f3acb299a04b0027a14481d2436be1c26074356e89a0536da4c1c8
license    : MIT
component  : system.utils
summary    : tmux session manager
description: |
    tmux session manager, built on libtmux.
homepage   : http://tmuxp.git-pull.com/
rundeps    :
    - python-click
    - python-colorama
    - python-libtmux
    - python-kaptan
    - tmux
build      : |
    %python3_setup
install    : |
    %python3_install
