name       : tmuxp
version    : 1.19.0
release    : 11
source     :
    - https://files.pythonhosted.org/packages/5d/ce/153ee0397dd99bae47c3a6ce68f990d186f5c9c9d9f0c8b4d51b62cd0ad5/tmuxp-1.19.0.tar.gz : 18490797f1428af8c96176ff7a4de2b97b3ad15aad8f8adbd9e8e0e8e647d9ff
license    : MIT
component  : system.utils
summary    : tmux session manager
description: |
    tmux session manager, built on libtmux.
homepage   : http://tmuxp.git-pull.com/
rundeps    :
    - python-colorama
    - python-libtmux
    - python-kaptan
    - tmux
build      : |
    %python3_setup
install    : |
    %python3_install
